### ISSUE TITLE
[Results UI] Make id smaller and response bigger

### ISSUE THREAD

**Issue by egekorkan** [tum-esi/wade#44]
from Readme.md:
```
(+) Results UI: Make id smaller (write -> w, read -> r ...) and response bigger -> display as obj
```

**Comment by miguelrk** [comment]
I came up with 2 alternatives to solve this:

**Option 1:** good that interactionName (e.g. r, w, o) comes at the end, which is better for cases where no interactionName is present (e.g. actions)
![option1](https://user-images.githubusercontent.com/18708856/87418643-50587580-c5d2-11ea-90d2-9ed87efcfed6.png)

**Option 2:** I find it visually more appealing, but it breaks consistency since properties are preceeded by it, but actions and events are not (see image)
![option2](https://user-images.githubusercontent.com/18708856/87418644-50f10c00-c5d2-11ea-9b58-cd198c70e58c.png)

**Comment by egekorkan** [comment]
I agree with the (r) and (w) kind of annotations. 
Regarding wrapping the responses in another object is misleading. Some implementations actually return this kind of response already and this would give the impression that every implementation does this. I would say that the response should never be wrapped into another object.

**Comment by miguelrk** [comment]
> Regarding wrapping the responses in another object is misleading. Some implementations actually return this kind of response already and this would give the impression that every implementation does this. I would say that the response should never be wrapped into another object.

Makes sense, wade shouldn't assume/enforce anything which is implementation-dependant. Will fall-back to non-object results for properties, action and event.

**Comment by egekorkan** [comment]
Fixed in master
