### ISSUE TITLE
[Editor] Monaco Editor does not resize with window

### ISSUE THREAD

**Issue by Fady222** [tum-esi/wade#88]
When the window is resized, the Monaco Editor does not resize to fill its container. The editor maintains its initial proportions at the moment of rendering.

**Comment by miguelrk** [comment]
This had already been fixed with pure css. Something broke I guess but this should work on the target editor element:
```css
div {
  resize: vertical;
  overflow: auto;
}
```

An alternative is to add the following to the options property of MonacoEditor (pass it into the component as option prop)
```css
automaticLayout: true
```

@Fady222 could you maybe try this? I'm having issues with electron:serve still. Thanks!
